### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by dgateles** [saintmac/fetch-upload-s3#7]
Hello
How to use this? Im using node.js but the file does not upload
fus3.do('https://nodejs.org/images/logo.png', 'my_key' ( what is my_key?)

**Comment by saintmac** [comment]
Hi @dgateles,
Do you do `fus3.init` (as stated in the documentation, before `fus3.do`?
Have you put your correct S3 keys?

To answer your question, `'my_key'` is the key you want this image to be referred as in your S3 bucket.
Here for instance it would be `'node_logo.png'`

Hope it helps

Martin

**Comment by dgateles** [comment]
Look: http://i.imgur.com/Bi6NnZW.png
As you can see, do not upload

**Comment by saintmac** [comment]
@dgateles super old thread, but your screenshot shows that the file has indeed been uploaded to S3.  Not sure what data is supposed to be in your code, but the library doesn't return any data in case of success, just an error in case of failure.
